#!/bin/sh

HOST=`bk gethost`
case "$HOST" in
 deacon.udel.edu) ;;
 whimsy.udel.edu) ;;
 *) exit 0 ;;
esac

echo Starting 'changelog' trigger

set -x

if [ X$BK_STATUS = XDRYRUN -o X$BK_STATUS = XNOTHING ]
then
    exit 0
fi
if [ $BK_SIDE = server ]
then
    U=$BKD_USER
    H=$BKD_HOST
    R=$BKD_ROOT
else
    U=$BK_USER
    H=$BK_HOST
    R=$BK_ROOT
fi
(
    if [ X$BKD_ROOT != X ]
    then
	printf '%-10s%-20s%-20s\n' VAR CLIENT SERVER
	printf '%-10s%-20s%-20s\n' === ====== ======
	printf '%-10s%-20s%-20s\n' USER $BK_USER $BKD_USER
	printf '%-10s%-20s%-20s\n' HOST $BK_HOST $BKD_HOST
	printf '%-10s%-20s%-20s\n' ROOT $BK_ROOT $BKD_ROOT
	printf '%-10s%-20s%-20s\n' LEVEL $BK_LEVEL $BKD_LEVEL
	printf '%-10s%-20s%-20s\n' TIME_T $BK_TIME_T $BKD_TIME_T
	printf '%-10s%-20s%-20s\n' UTC $BK_UTC $BKD_UTC
	printf '%-10s%-20s%-20s\n' VERSION $BK_VERSION $BKD_VERSION
	echo
    fi
    echo ${U}@${H} fired the $BK_TRIGGER trigger in $R
    (
    case $BK_TRIGGER in
     pre-outgoing*)   VERB=Sending;;
     post-outgoing*)  VERB=Sent;;
     pre-incoming*)   VERB=Receiving;;
     post-incoming*)  VERB=Received;;
     pre-resolve*)    VERB=Resolving;;
     pre-commit*)     VERB=Committing;;
     post-commit*)    VERB=Committed;;
     pre-apply*)      VERB=Applying;;
     *)		      VERB="$BK_TRIGGER for";;
    esac
    echo $VERB the following changesets
    echo
    bk changes -v -r+
    ) | sed 's/^/    /'
) | mail -s "$BK_EVENT in ${H}:${R}" cvs-all@ntp.org

echo Leaving 'changelog' trigger
exit 0
