#! /bin/sh

HOST=`bk gethost`
case "$HOST" in
 deacon.udel.edu) ;;
 whimsy.udel.edu) ;;
 *) exit 0 ;;
esac

LGC=
test -f ${bkp}BitKeeper/triggers/.lgc && LGC=`cat ${bkp}BitKeeper/triggers/.lgc`

case "$LGC" in
 '') exit 1 ;;
esac

if [ X$BK_STATUS = XDRYRUN -o X$BK_STATUS = XNOTHING ]
then
    echo "Bailed - BK_STATUS is <$BK_STATUS>"
    exit 0
fi
if [ $BK_SIDE = server ]
then
    U=$BKD_USER
    H=$BKD_HOST
    R=$BKD_ROOT
else
    U=$BK_USER
    H=$BK_HOST
    R=$BK_ROOT
fi
#mail -s 'BO good stuff' stenn@ntp.org < /dev/null
(
    if [ X$BKD_ROOT != X ]
    then
	printf '%-10s%-20s%-20s\n' VAR CLIENT SERVER
	printf '%-10s%-20s%-20s\n' === ====== ======
	printf '%-10s%-20s%-20s\n' USER $BK_USER $BKD_USER
	printf '%-10s%-20s%-20s\n' HOST $BK_HOST $BKD_HOST
	printf '%-10s%-20s%-20s\n' ROOT $BK_ROOT $BKD_ROOT
	printf '%-10s%-20s%-20s\n' LEVEL $BK_LEVEL $BKD_LEVEL
	printf '%-10s%-20s%-20s\n' TIME_T $BK_TIME_T $BKD_TIME_T
	printf '%-10s%-20s%-20s\n' UTC $BK_UTC $BKD_UTC
	printf '%-10s%-20s%-20s\n' VERSION $BK_VERSION $BKD_VERSION
	echo
    fi
    echo ${U}@${H} fired the $BK_TRIGGER trigger in $R
    (
    case $BK_TRIGGER in
     pre-outgoing*)   VERB=Sending;;
     post-outgoing*)  VERB=Sent;;
     pre-incoming*)   VERB=Receiving;;
     post-incoming*)  VERB=Received;;
     pre-resolve*)    VERB=Resolving;;
     pre-commit*)     VERB=Committing;;
     post-commit*)    VERB=Committed;;
     pre-apply*)      VERB=Applying;;
     *)		      VERB="$BK_TRIGGER for";;
    esac
    echo $VERB the following changesets
    echo

    bk -R prs -hr${LGC}.. -x1st -nd':I:' | bk changes -v -
    ) | tee ChangeLog.new | sed 's/^/    /'
) | mail -s "$BK_EVENT in ${H}:${R}" commitlogs@ntp.org
#cat ChangeLog >> ChangeLog.new
#mv ChangeLog.new ChangeLog

