# Automatically generated by configure - do not modify
SRC_PATH=/home/situlingyun/Documents/protocol-fuzzer/afl-2.39b-net/qemu_mode/qemu-2.3.0/roms/vgabios
AS=as
CC=clang
BCC=bcc
CPP=clang -E
OBJCOPY=objcopy
IASL=iasl
LD=ld
